### ISSUE TITLE
Setup nbdev and add parsing tests with a single pdf

### ISSUE THREAD

**Issue by NirantK** [NirantK/projectnoor#6]

**Comment by meghanabhange** [comment]
Giving up on this. Can't get it to work because of conflicting files with fastpages :(

**Comment by NirantK** [comment]
Deciding to not do this for now. 

## Why? 

What we want is the Github Actions for making the python scripts from notebook, but not the HTML docs which would conflict with fastpages. 

Given that nbdev does both by default, and @meghanabhange couldn't figure out a way to do only script generation -- marking this as a "Help Wanted" but not closing it. Also, removing the person assignment.
